### ISSUE TITLE
5月20日TFまでのTODO

### ISSUE THREAD

**Issue by Y-Wakuta** [AlbatrossAvionics/Alba-2017#34]
- [x] トワイライトのアンテナを変える・コクぴの上側に着ける・振動から受ける影響を確認 #35 
- [ ] ロガーの調整（グラフの描画速度を速くする・欠損率とかも表示する・テクストボックスをkei/con/inpように作成）#36
- [x] Androidのフライト用画面を表示できるようにする #37 
- [ ] AndroidでBlueTooth接続できなかったら、つながるまで、接続を試みるようにする。#37
- [x] ロールアラームの範囲を狭くする #38 
- [x] 左ドラッグラダーのスイッチ基板の接触を改善（小さい基板やし、作りなおそう。今度は大きめに作ってジョイスティックに張り付けれるように。）#39
- [ ] ジョイスティックの入力に対して、エレボンが不安定な時があったから、原因究明 #40 
- [x] 右翼端基板が基板にmbedをつけた状態で書き込めなかった原因の究明（どっかでショート？）#43
- [ ] ニュートラルの値範囲を入力に対して大きくする。大きくした上で、段階数を増加 #40
- [x] 風速計を今年買ったセンサでできないか再度考える。 #42
- [x] ジョイスティックが２軸目が動いてしまってるからそれを固定
- [x] 高度計の調整  #41
